// swift-tools-version: 6.0

// WARNING:
// This file is automatically generated.
// Do not edit it by hand because the contents will be replaced.

import PackageDescription
import AppleProductTypes

let package = Package(
    name: "Focuspace",
    platforms: [
        .iOS("17.0")
    ],
    products: [
        .iOSApplication(
            name: "Focuspace",
            targets: ["AppModule"],
            bundleIdentifier: "com.twilightvoyager777.focuspace",
            teamIdentifier: "UG9QCW355W",
            displayVersion: "1.0",
            bundleVersion: "1",
            appIcon: .asset("AppIcon"),
            accentColor: .presetColor(.orange),
            supportedDeviceFamilies: [
                .pad,
                .phone
            ],
            supportedInterfaceOrientations: [
                .portrait(.when(deviceFamilies: [.phone])),
                .landscapeRight,
                .landscapeLeft
            ],
            capabilities: [
                .camera(purposeString: "Use the camera to compose and capture photos and videos."),
                .microphone(purposeString: "Record audio when capturing videos."),
                .photoLibrary(purposeString: "Export captured photos and videos to your Photos library.")
            ],
            appCategory: .photography
        )
    ],
    targets: [
        .executableTarget(
            name: "AppModule",
            path: "."
        )
    ],
    swiftLanguageVersions: [.version("6")]
)
